// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Api.Infrastructure.Data;

namespace Restaurant.Api.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20200510204432_ChangeColumn")]
    partial class ChangeColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Restaurant.Api.Infrastructure.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Restaurant.Api.Infrastructure.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Restaurant.Api.Infrastructure.Models.RestaurantConfig", b =>
                {
                    b.Property<Guid>("RestaurantConfigId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FontFamily");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Logo");

                    b.Property<string>("PrimaryColor");

                    b.Property<string>("RestaurantName");

                    b.HasKey("RestaurantConfigId");

                    b.ToTable("RestaurantConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
